# .gitlab-ci.yml
# GitLab CI pipeline to build, test, and prepare the FastAPI inference service

stages:
  - build
  - test
  - package

variables:
  IMAGE_NAME: cicids-inference
  TAG: latest

build:
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t $IMAGE_NAME:$TAG inference_service/

unit_test:
  stage: test
  script:
    - echo "Running test client against local API"
    - docker run -d --rm -p 8000:8000 --name test_app -v $CI_PROJECT_DIR/inference_service/model.joblib:/app/model.joblib $IMAGE_NAME:$TAG
    - sleep 5  # allow the container to boot
    - python3 inference_service/test_client.py
    - docker stop test_app

save_image:
  stage: package
  script:
    - echo "Saving Docker image as artifact"
    - docker save -o cicids-inference.tar $IMAGE_NAME:$TAG
  artifacts:
    paths:
      - cicids-inference.tar

