apiVersion: v1
kind: Service
metadata:
  name: cicids-inference-service
spec:
  selector:
    app: cicids-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

