apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicids-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicids-inference
  template:
    metadata:
      labels:
        app: cicids-inference
    spec:
      containers:
        - name: inference-service
          image: cicids-inference:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

