apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicids-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicids-inference
  template:
    metadata:
      labels:
        app: cicids-inference
    spec:
      containers:
        - name: inference-service
          image: cicids-inference:latest # This will be replaced by CI/CD pipeline
          imagePullPolicy: Always # Ensures the latest image is pulled for tags like commit SHAs
          ports:
            - containerPort: 8000
          # These are starting values and should be adjusted based on
          # performance monitoring and load testing.
          resources:
            requests:
              cpu: "100m" # 0.1 CPU core
              memory: "128Mi" # 128 Mebibytes
            limits:
              cpu: "500m" # 0.5 CPU core
              memory: "512Mi" # 512 Mebibytes
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

